# Generated by Django 4.1.2 on 2022-11-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placer',
            name='a101_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a101_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a102_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a102_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a103_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a103_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a104_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a104_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a105_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a105_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d10/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a11_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a11_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a12_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a12_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a13_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a13_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a14_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a14_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a15_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a15_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d1/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a21_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a21_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a22_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a22_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a23_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a23_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a24_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a24_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a25_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a25_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d2/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a31_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a31_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a32_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a32_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a33_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a33_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a34_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a34_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a35_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a35_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d3/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a41_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a41_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a42_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a42_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a43_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a43_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a44_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a44_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a45_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a45_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d4/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a51_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a51_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a52_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a52_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a53_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a53_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a54_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a54_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a55_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a55_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d5/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a61_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a61_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a62_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a62_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a63_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a63_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a64_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a64_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a65_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a65_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d6/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a71_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a71_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a72_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a72_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a73_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a73_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a74_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a74_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a75_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a75_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d7/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a81_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a81_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a82_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a82_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a83_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a83_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a84_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a84_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a85_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a85_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d8/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a91_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h1 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a91_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h1 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a92_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h2 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a92_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h2 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a93_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h3 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a93_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h3 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a94_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h4 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a94_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h4 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a95_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h5 normals+', to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='a95_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, related_name='d9/h5 spesifics+', to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.places', verbose_name='place area'),
        ),
        migrations.AddField(
            model_name='placer',
            name='existence_of_classic_activities',
            field=models.ManyToManyField(blank=True, null=True, to='activities.classic_activities', verbose_name='classic_activites'),
        ),
        migrations.AddField(
            model_name='placer',
            name='existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, to='activities.classic_room', verbose_name='normal game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, to='activities.non_classic_activity_room', verbose_name='spesific game existence'),
        ),
        migrations.AddField(
            model_name='placer',
            name='username',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='message_manager',
            name='chatbox',
            field=models.ManyToManyField(blank=True, null=True, related_name='between_two_ferns+', to='account.between_two_ferns', verbose_name='messages'),
        ),
        migrations.AddField(
            model_name='message_manager',
            name='whos_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='peoplein+', to='account.consumer', verbose_name='whos in'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='c_room_offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='croom_query+', to='activities.classic_room', verbose_name='game querys normal'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats+', to='account.message_manager', verbose_name='messages'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friendsquery+', to='account.consumer', verbose_name='friendsquery'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='friendsquery',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends+', to='account.consumer', verbose_name='friends'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='ibanned',
            field=models.ManyToManyField(blank=True, null=True, related_name='banned+', to='account.consumer', verbose_name='ibanned'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='imbanned',
            field=models.ManyToManyField(blank=True, null=True, related_name='imbanned+', to='account.consumer', verbose_name='imbanned'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='in_classics',
            field=models.ManyToManyField(blank=True, null=True, to='activities.classic_room', verbose_name='which type of game exists'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='in_non_classics',
            field=models.ManyToManyField(blank=True, null=True, to='activities.non_classic_activity_room', verbose_name='in which spesific games'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='n_room_offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='nroom_query+', to='activities.non_classic_activity_room', verbose_name='game querys not normal'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.universities', verbose_name='university'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='username',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='between_two_ferns',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.consumer', verbose_name='area'),
        ),
        migrations.AddField(
            model_name='between_two_ferns',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.message_manager', verbose_name='area'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.places', verbose_name='place area'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='in_classics_existence_of_normal_game',
            field=models.ManyToManyField(blank=True, null=True, to='activities.classic_room', verbose_name='in which normal games'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='in_non_classics_existence_of_not_normal_game',
            field=models.ManyToManyField(blank=True, null=True, to='activities.non_classic_activity_room', verbose_name='in which spesific games'),
        ),
        migrations.AddField(
            model_name='usercore',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.universities', verbose_name='university'),
        ),
    ]
