# Generated by Django 4.1.2 on 2022-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('account', '0003_consumer_p_room_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='in_placer_rooms',
            field=models.ManyToManyField(blank=True, null=True, to='activities.placer_room', verbose_name='which type of placer game exists'),
        ),
    ]
