# Generated by Django 4.1.2 on 2022-11-28 20:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_consumer_in_placer_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='between_two_ferns_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_itself', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name')),
                ('c_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='message_manager_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbox', models.ManyToManyField(blank=True, null=True, related_name='between_two_ferns+', to='account.between_two_ferns_2', verbose_name='messages')),
                ('whos_in', models.ManyToManyField(blank=True, null=True, related_name='peoplein+', to=settings.AUTH_USER_MODEL, verbose_name='whos in')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='place mail adress')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='uploads/community', verbose_name='pic1')),
                ('phone', models.IntegerField(unique=True, verbose_name='phone')),
                ('ranking', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ranking')),
                ('money', models.IntegerField(blank=True, default=0, null=True, verbose_name='money')),
                ('verify', models.BooleanField(default=True, verbose_name='can avaliable')),
                ('verify_pic', models.ImageField(blank=True, null=True, upload_to='uploads/consumers/', verbose_name='vpic')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('chats', models.ManyToManyField(blank=True, null=True, related_name='chats+', to='account.message_manager_2', verbose_name='messages')),
            ],
        ),
    ]
