# Generated by Django 4.1.2 on 2022-11-28 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_placer_room_query'),
        ('account', '0005_between_two_ferns_2_message_manager_2_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='p_room_offers_to_p',
            field=models.ManyToManyField(blank=True, null=True, related_name='proom_query+', to='activities.placer_room_query', verbose_name='game querys placer'),
        ),
        migrations.AddField(
            model_name='community',
            name='username',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='between_two_ferns_2',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='between_two_ferns_2',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.message_manager_2', verbose_name='area'),
        ),
    ]
