# Generated by Django 4.1.2 on 2022-11-28 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_community_p_room_offers_to_p_community_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='user_type',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='user type'),
        ),
    ]
