# Generated by Django 4.1.2 on 2022-11-28 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_usercore_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
    ]
