# Generated by Django 4.1.2 on 2022-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercore',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats+', to='account.message_manager_2', verbose_name='messages'),
        ),
    ]
