# Generated by Django 4.1.2 on 2022-11-28 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_between_two_ferns_2_message_manager_2_community'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placer_room_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('game_type', models.CharField(max_length=50, verbose_name='activity')),
                ('m_time', models.DateTimeField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField()),
                ('max_ppl_existence', models.IntegerField(blank=True, verbose_name='activity capacity')),
                ('entry_price', models.IntegerField(verbose_name='entry price')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('if_its_anywhere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.places', verbose_name='spesific activity place')),
                ('offers', models.ManyToManyField(related_name='wants to be in loby1+', to='account.consumer', verbose_name='wants to be in loby')),
                ('ppl_existence', models.ManyToManyField(blank=True, null=True, to='account.consumer', verbose_name='in loby')),
            ],
        ),
    ]
