# Generated by Django 4.1.2 on 2022-11-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_community_name'),
        ('activities', '0002_placer_room_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placer_room_query',
            name='if_its_anywhere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.placer', verbose_name='spesific activity place'),
        ),
    ]
