# Generated by Django 4.1.2 on 2022-11-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_placer_room_query_room_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='placer_room',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='contact'),
        ),
    ]
