# Generated by Django 4.1.2 on 2023-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_places_pic1_alter_places_pic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placer_room',
            name='fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='entry price'),
        ),
        migrations.AddField(
            model_name='placer_room',
            name='pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='entry price'),
        ),
        migrations.AddField(
            model_name='placer_room_query',
            name='fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='entry price'),
        ),
        migrations.AddField(
            model_name='placer_room_query',
            name='pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='entry price'),
        ),
    ]
