# Generated by Django 4.1.2 on 2023-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_placer_room_query_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='placer_room',
            name='offerprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='entry price'),
        ),
    ]
