# Generated by Django 4.1.2 on 2023-07-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0007_alter_places_pic1_alter_places_pic2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/wallpics/', verbose_name='post görseli')),
                ('text', models.CharField(max_length=30, verbose_name='içerik')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.places', verbose_name='konum')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
                ('hashtag_croom', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.classic_room', verbose_name='varsa croom')),
                ('hashtag_nroom', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.non_classic_activity_room', verbose_name='varsa nroom')),
                ('hashtag_proom', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.placer_room', verbose_name='varsa proom')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='liker')),
            ],
        ),
    ]
