# Generated by Django 4.1.2 on 2023-07-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='içerik'),
        ),
    ]
