# Generated by Django 4.1.2 on 2023-07-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_alter_wallpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='içerik'),
        ),
    ]
