# Generated by Django 4.1.2 on 2023-07-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_places_pic1_alter_places_pic2_and_more'),
        ('wall', '0003_alter_wallpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='hashtag_croom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.classic_room', verbose_name='varsa croom'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='hashtag_nroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.non_classic_activity_room', verbose_name='varsa nroom'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='hashtag_proom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.placer_room', verbose_name='varsa proom'),
        ),
    ]
