# Generated by Django 4.1.2 on 2023-08-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_alter_wallpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/wallpics', verbose_name='post görseli'),
        ),
    ]
