# Generated by Django 4.1.2 on 2023-08-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_alter_wallpost_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
