# Generated by Django 4.1.2 on 2023-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_remove_wallpost_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
